/***************************************************************************************************
Class Name: customException
Class Type: Exception Handler 
Version     : 1.0 
Created Date: 17 June 2016
Function    : This class helps in throwing custom exceptions from a try block and the message is obtained in the catch block 
Input Parameters: None 
Output Parameters: None
Description:   This class just extends Exception class(Apex Class)
Used in     : Custom Exceptions
Modification Log :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* JRK                        06/17/2016              Created
****************************************************************************************************/
public class customException extends Exception{}